# Generated by Django 5.1.3 on 2024-12-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='image',
            new_name='itemimage',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='title',
            new_name='itemname',
        ),
        migrations.RemoveField(
            model_name='items',
            name='desc',
        ),
        migrations.AddField(
            model_name='items',
            name='itemabout',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='itemprice',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
