# Generated by Django 5.1.3 on 2025-01-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefimg', models.CharField(max_length=3000)),
                ('chefsname', models.CharField(max_length=30)),
                ('chefpostion', models.CharField(max_length=30)),
                ('chefinfo', models.CharField(max_length=20)),
            ],
        ),
    ]
