# Generated by Django 5.1.3 on 2025-01-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimg', models.CharField(max_length=30)),
            ],
        ),
    ]
