# Generated by Django 5.1.3 on 2025-01-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
